Feature/task 3
ozonmp/edu-solution-api pull request #2
Opened 2021-11-02 21:13 UTC by Miklch17

Возможно попадуться какие-то куски из  прошлой домашки, но вроде постарался их в другую ветку закинуть.

2021-11-04 09:09 UTC, grozauf requested changes

2021-11-04 09:09 UTC, grozauf commented on internal/api/api_CreateSolutionV1.go
> +		log.Debug().Uint64("TaskId", req.TaskId).Uint64("TaskId", req.TaskId).Str("Description", req.Description).Msg("solution not found")
Объект ведь только создаётся. Почему он может быть not found?

2021-11-04 09:09 UTC, grozauf commented on internal/api/api_CreateSolutionV1.go
> +	solution, err := o.repo.CreateSolution(ctx, req.TaskId, req.TaskId, req.Description)
думаю, что из Create достаточно возвратить id созданного объекта. Все остальные данные в вызывающей функции есть.

2021-11-04 09:09 UTC, grozauf commented on internal/api/api_ListSolutionV1.go
> +	solution, err := o.repo.ListSolution(ctx, req.Start, req.Offset)
solutions
solutionList

2021-11-04 09:09 UTC, grozauf commented on internal/api/api_ListSolutionV1.go
> +func Convert(solution []model.Solution) []*pb.Solution {
Экспортируемая?

2021-11-04 09:09 UTC, grozauf commented on api/ozonmp/edu_solution_api/v1/edu_solution_api.proto
> +  string result = 1;
может bool?

2021-11-04 09:09 UTC, grozauf commented on internal/api/api_RemoveSolutionV1.go
> +		log.Debug().Uint64("SolutionId", req.SolutionId).Msg("solution not found")
Ошибка может говорить о внутренней ошибке (доступ к базе или ещё что-то). Обычно Remove возвращает bool, err. Если false, nil - то значит not found и т.д.

2021-11-04 09:09 UTC, grozauf commented on internal/api/api_RemoveSolutionV1.go
> +	solution, err := o.repo.RemoveSolution(ctx, req.SolutionId)
result
isRemoved

2021-11-04 09:11 UTC, grozauf commented on api/ozonmp/edu_solution_api/v1/edu_solution_api.proto
> +      get: "/v1/solution/describe/{solution_id}"
Чисто к сведению:

POST /api/v1/solution - создание
GET /api/v1/solution - вывод списка
GET /api/v1/solution/{id} - вывод одного по id
DELETE /api/v1/solution/{id} - удаление одного по id
PUT /api/v1/solution/{id} - апдейт одного по id

2021-11-04 09:23 UTC, grozauf commented on api/ozonmp/edu_solution_api/v1/edu_solution_api.proto
> +  uint64 start = 1 [(validate.rules).uint64.gt = 0];
start и offset - это одно и тоже. limit, offset обычно используются

2021-11-04 18:49 UTC, Miklch17 commented on internal/api/api_CreateSolutionV1.go
> +	solution, err := o.repo.CreateSolution(ctx, req.TaskId, req.TaskId, req.Description)
Я считаю что лучше возвращать объект как более универсальный вариант, т.к. над входными данными могут применяется преобразования (форматирование номера телефона, как пример) + могут быть вычисляемые поля, и обо всем этом вызывающая сторона не знает, пока не получит созданный объект

2021-11-04 18:54 UTC, Miklch17 commented on api/ozonmp/edu_solution_api/v1/edu_solution_api.proto
> +      get: "/v1/solution/describe/{solution_id}"
list оставлю put, т.к. если я правильно помню, то в get параметры не принято передавать через тело запроса.

2021-11-05 15:14 UTC, grozauf commented on api/ozonmp/edu_solution_api/v1/edu_solution_api.proto
> +      get: "/v1/solution/describe/{solution_id}"
PUT используется для апдейта данных. Не для получения.

2021-11-05 15:22 UTC, grozauf commented on internal/api/api_ListSolutionV1.go
> +	solutions, err := o.repo.ListSolution(ctx, req.Start, req.Offset)
Только сейчас заметил, что ListSolution возвращает указатель на слайс. Слайс - это небольшая структура с указателем, поэтому это лишнее

2021-11-05 15:23 UTC, grozauf commented on internal/api/api_RemoveSolutionV1.go
> +	if !isRemoved && err == nil {
Это условие можно выполнить после проверки err != nil

2021-11-05 15:24 UTC, grozauf commented on docker-compose.yaml
> +  pipyserver:
желательно ещё поправить питон-клиента. добавить туда использование своих функций, сейчас там template

2021-11-05 15:24 UTC, grozauf approved these changes

2021-11-05 19:29 UTC, Miklch17 commented on api/ozonmp/edu_solution_api/v1/edu_solution_api.proto
> +  uint64 start = 1 [(validate.rules).uint64.gt = 0];
start - номер/ID первого элемента
offset - смещение/кол-во

limit тут не очень подходит возможно begin_id или first_id

2021-11-06 17:18 UTC, merged