Feature/task 4
ozonmp/edu-solution-api pull request #3
Opened 2021-11-09 21:53 UTC by Miklch17

2021-11-11 11:14 UTC, grozauf requested changes

2021-11-11 11:14 UTC, grozauf commented on internal/repo/event.go
> +		s, args, err := query.ToSql()
Не обязательно приводить в Sql. Через query можно также всё необходимое вызывать. Надо только указать RunWith() в query

2021-11-11 11:14 UTC, grozauf commented on internal/repo/repo.go
> +	var res []model.Solution
зачем слайс, если получается только один элемент?

2021-11-11 11:14 UTC, grozauf commented on internal/repo/repo.go
> +	}
А добавление евента?

2021-11-11 11:35 UTC, Miklch17 commented on api/ozonmp/edu_solution_api/v1/edu_solution_api.proto
> +  string description = 3 [(validate.rules).string = {min_len:5, max_len:2000}];
описание менее 5 букв думаю не реально, я бы еще больше поставил, мы такое используем как защиту от дурака

2021-11-11 11:37 UTC, Miklch17 commented on config.yml
> +  host: pg_con
это была очень тяжелая борьба за понимание как это должно работать, чтобы  не падало и возможно между тем как стер и написал заново прошло 3-6 часов. главное работает.

2021-11-11 11:39 UTC, Miklch17 commented on internal/model/education.go
> +	createdST       = "Created"
должно быть ET т.к. константы нужны для конвертации EvnetType. Заменю на полные названия

2021-11-11 11:42 UTC, Miklch17 commented on internal/repo/event.go
> +		s, args, err := query.ToSql()
как на лекции показывали, пока оставлю так, изменю это в самом конце.

2021-11-11 11:43 UTC, Miklch17 commented on internal/repo/repo.go
> +	}
а это забыл, как раз сейчас доделываю

2021-11-12 12:02 UTC, grozauf requested changes

2021-11-12 12:02 UTC, grozauf commented on migrations/DataSet.sql
> +insert into public.solution (task_id, student_id, description)
Вставлять несколько строк можно более изящно https://www.postgresqltutorial.com/postgresql-insert-multiple-rows/
И накатку датасета лучше добавить в миграцию

2021-11-14 16:40 UTC, merged