Feature/task 5
ozonmp/edu-solution-api pull request #4
Opened 2021-11-17 18:09 UTC by Miklch17

2021-11-18 13:52 UTC, grozauf requested changes

2021-11-18 13:52 UTC, grozauf commented on cmd/edu-solution-api/main.go
> +	http.ListenAndServe(":"+string(cfg.Metrics.Port), nil)
надо проверять ошибку.
ListenAndServe блокирующий вызов. тут он проходит т.к. возвращает ошибку, потому что порт кривой
string(int) - нельзя так: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)

2021-11-18 13:52 UTC, grozauf commented on cmd/edu-solution-api/main.go
> +		notSugaredLogger.Sync()
желательно тоже проверять ошибку

2021-11-18 13:52 UTC, grozauf commented on cmd/grpc-server/main.go
> +func initLogger(ctx context.Context, cfg config.Config) (syncFn func()) {
подобные одинаковые функции можно вынести в отдельный пакет + main.go из-за них становится большим, лучше в нём держать минимум

2021-11-18 13:52 UTC, grozauf commented on cmd/grpc-server/main.go
> +func initTracer(ctx context.Context, cfg config.Config) (closer io.Closer) {
также функция дублируется

2021-11-18 13:52 UTC, grozauf commented on internal/repo/event_Add.go
> +		totalSolutionCUD.Inc()
количество CRUD логичнее считать в CRUD ручках или в repo.go

2021-11-18 13:52 UTC, grozauf commented on internal/repo/event_Lock.go
> +	logger.DebugKV(ctx, "Lock - start")
Lock() отрабатывает по таймауту каждые 10 микросекунд. Думаю, что это слишком маленький таймаут.
+ судя по логам Lock() постоянно вызывается и никак не закончится, что странно, т.к. тестовые данные конечны и по идее должны обработаться за конечное число локов, но он постоянно вызывается. Может где-то не меняется состояние данных - что они обработаны?

2021-11-18 19:52 UTC, Miklch17 commented on internal/repo/event_Add.go
> +		totalSolutionCUD.Inc()
перенес, но встал вопрос: есть групповые операции, и работают только группой, для экономии ресурсов не проще ли подавать сразу результат,  а не пихать в счетчик по 1 штуке

2021-11-18 19:56 UTC, Miklch17 commented on internal/repo/event_Lock.go
> +	logger.DebugKV(ctx, "Lock - start")
Как по мне так это как раз нормально, или я что-то не правильно понял? Время можно поднять это не проблема. Но задача сервиса же перекладывать в кафку и начало цепочки идет через Lock(), поэтому если данных нет, то у нас получается вечное срабатывание Lock() до тех пор пока не появятся данные. Опять же что считать нормальной частотой срабатывания? чем больше интервал, тем позже данные дойдут ко кафки, т.к. они позже будут заблочены. Пока исправлю на 1 сек, чтобы не спамить запросы на виртуалках

2021-11-19 07:00 UTC, grozauf approved these changes

2021-11-20 18:13 UTC, merged